[package]
name = "vms-gateway"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
webrtc = "0.20.3"
rtc = "0.20.3"
digest_auth = "0.3.1"
bytes = "1.12"
async-trait = "0.1"
anyhow.workspace = true
base64 = "0.22"
chrono.workspace = true
futures = "0.3"
quick-xml = "0.38"
rand = "0.8"
reqwest.workspace = true
retina = "0.4.20"
sha1 = "0.10"
serde.workspace = true
serde_json.workspace = true
shiguredo_mp4 = "2026.4.0"
url = "2"
uuid = { workspace = true, features = ["v5"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
vms-domain = { path = "../../crates/domain" }
vms-plugin-sdk = { path = "../../crates/plugin-sdk" }
