[package]
name = "vms-plugin-runtime"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
vms-plugin-sdk = { path = "../plugin-sdk" }
